// The ad category taxonomy: every category belongs to exactly one group.
// Groups are only for browsing (the library's "Browse all categories");
// an ad stores the category name itself.
export const CATEGORY_GROUPS: { name: string; categories: string[] }[] = [
  {
    name: "Fashion & Apparel",
    categories: [
      "Fashion",
      "Apparel",
      "Luxury Fashion",
      "Streetwear",
      "Activewear",
      "Footwear",
      "Sneakers",
      "Lingerie",
      "Swimwear",
      "Menswear",
      "Womenswear",
      "Kidswear",
      "Plus-Size Fashion",
      "Modest Fashion",
      "Vintage Clothing",
      "Outerwear",
      "Denim",
      "Workwear",
      "Eyewear",
      "Sunglasses",
      "Handbags",
      "Jewelry",
      "Watches",
      "Accessories",
      "Hats",
      "Ethical Fashion",
      "Fast Fashion",
      "Bridal",
      "Kids' Shoes",
      "Socks",
      "Underwear",
      "Sleepwear",
      "Maternity Wear",
      "Uniforms",
      "Costumes",
    ],
  },
  {
    name: "Beauty & Personal Care",
    categories: [
      "Beauty",
      "Skincare",
      "Makeup",
      "Haircare",
      "Fragrance",
      "Nail Care",
      "Clean Beauty",
      "K-Beauty",
      "Men's Grooming",
      "Shaving",
      "Beard Care",
      "Oral Care",
      "Sun Care",
      "Anti-Aging",
      "Body Care",
      "Tattoos",
      "Hair Removal",
      "Self-Tanning",
      "Lashes",
      "Brows",
      "Wigs",
      "Hair Tools",
      "Hair Loss",
    ],
  },
  {
    name: "Health & Wellness",
    categories: [
      "Health",
      "Healthcare",
      "Mental Wellness",
      "Supplements",
      "Vitamins",
      "Nutrition",
      "Weight Loss",
      "Sleep",
      "Meditation",
      "Telehealth",
      "Pharmacy",
      "OTC Medicine",
      "Sexual Wellness",
      "Women's Health",
      "Menopause",
      "Fertility",
      "Pregnancy Tests",
      "Hearing Care",
      "Medical Devices",
      "Dental Care",
      "Optometry",
      "Contact Lenses",
      "Aesthetic Clinics",
      "Cosmetic Surgery",
      "Smoking Cessation",
      "Physiotherapy",
      "Chiropractic",
      "Orthopedics",
      "Diabetes Care",
      "Allergy Relief",
      "Pain Relief",
      "First Aid",
      "Mental Health Apps",
      "Therapy Platforms",
      "Addiction Recovery",
      "Gut Health",
      "Keto",
      "Fasting",
      "Massage",
      "Spas",
      "Saunas",
      "Cold Plunge",
      "DNA Testing",
      "Life Coaching",
    ],
  },
  {
    name: "Sports & Fitness",
    categories: [
      "Fitness",
      "Gyms",
      "Yoga",
      "Pilates",
      "Home Fitness Equipment",
      "Fitness Trackers",
      "Sports Nutrition",
      "Protein",
      "Sports",
      "Sports Equipment",
      "Sports Teams",
      "Running",
      "Marathons",
      "Cycling Gear",
      "Football",
      "Basketball",
      "Tennis",
      "Padel",
      "Golf",
      "Golf Courses",
      "Swimming",
      "Martial Arts",
      "Boxing",
      "Climbing",
      "Surfing",
      "Skateboarding",
      "Snowboarding",
      "Skiing",
      "Horse Riding",
      "Equestrian",
      "Fishing",
      "Hunting",
      "Archery",
      "Tactical Gear",
      "Camping",
      "Hiking",
      "Outdoor Gear",
    ],
  },
  {
    name: "Food & Drink",
    categories: [
      "Food",
      "Grocery",
      "Organic Food",
      "Plant-Based Food",
      "Snacks",
      "Confectionery",
      "Bakery",
      "Cereal",
      "Dairy",
      "Alt Dairy",
      "Meat",
      "Seafood",
      "Frozen Food",
      "Ready Meals",
      "Meal Kits",
      "Sauces",
      "Spices",
      "Cooking Oils",
      "Ice Cream",
      "Food Delivery",
      "Restaurants",
      "Fast Food",
      "Pizza",
      "Burgers",
      "Coffee Shops",
      "Bubble Tea",
      "Beverages",
      "Coffee",
      "Tea",
      "Water",
      "Kombucha",
      "Energy Drinks",
      "Non-Alcoholic Drinks",
      "Wine",
      "Beer",
      "Cider",
      "Hard Seltzer",
      "Spirits",
    ],
  },
  {
    name: "Home & Garden",
    categories: [
      "Home Decor",
      "Interior Design",
      "Furniture",
      "Outdoor Furniture",
      "Mattresses",
      "Bedding",
      "Rugs",
      "Candles",
      "Lighting",
      "Kitchenware",
      "Kitchens",
      "Bathroom",
      "Fireplaces",
      "Small Appliances",
      "Home Appliances",
      "Vacuum Cleaners",
      "Robot Vacuums",
      "Air Purifiers",
      "Water Filters",
      "Smart Home",
      "Home Security",
      "Cleaning Products",
      "Home Organization",
      "Storage Units",
      "Home Improvement",
      "DIY Tools",
      "Gardening",
      "Houseplants",
      "Pools",
      "Home Warranty",
    ],
  },
  {
    name: "Home Services & Property",
    categories: [
      "Cleaning Services",
      "Moving Services",
      "HVAC",
      "Heat Pumps",
      "Plumbing",
      "Electricians",
      "Roofing",
      "Windows",
      "Doors",
      "Flooring",
      "Paint",
      "Pest Control",
      "Locksmiths",
      "Construction",
      "Real Estate",
      "Property Management",
    ],
  },
  {
    name: "Family & Kids",
    categories: [
      "Parenting",
      "Maternity",
      "Baby Products",
      "Baby Food",
      "Baby Formula",
      "Breast Pumps",
      "Diapers",
      "Strollers",
      "Car Seats",
      "Nursery",
      "Toys",
      "Educational Toys",
      "Kids' Entertainment",
      "Childcare",
      "School Supplies",
      "Back to School",
      "Summer Camps",
      "Birthday Parties",
      "Baby Showers",
    ],
  },
  {
    name: "Pets",
    categories: [
      "Pets",
      "Pet Food",
      "Pet Supplements",
      "Dog Products",
      "Cat Products",
      "Pet Toys",
      "Pet Beds",
      "Pet Tech",
      "Pet Grooming",
      "Dog Training",
      "Pet Sitting",
      "Pet Insurance",
      "Veterinary Services",
      "Aquariums",
      "Bird Supplies",
      "Reptile Supplies",
      "Horse Care",
    ],
  },
  {
    name: "Life Events & Faith",
    categories: [
      "Weddings",
      "Dating",
      "Funerals",
      "Senior Care",
      "Retirement Homes",
      "Genealogy",
      "Religion",
      "Religious Organizations",
    ],
  },
  {
    name: "Shopping, Gifts & Hobbies",
    categories: [
      "Department Stores",
      "Discount Retail",
      "Gifts",
      "Greeting Cards",
      "Personalized Products",
      "Subscription Boxes",
      "Luxury Goods",
      "Collectibles",
      "Trading Cards",
      "Model Kits",
      "Puzzles",
      "Crafts",
      "Art Supplies",
      "Knitting",
      "Sewing",
      "Scrapbooking",
      "Stationery",
      "Calendars",
      "Photography",
      "Musical Instruments",
    ],
  },
  {
    name: "Travel",
    categories: [
      "Travel",
      "Flights",
      "Airlines",
      "Hotels",
      "Hostels",
      "Vacation Rentals",
      "Glamping",
      "Cruises",
      "Tours",
      "Travel Agencies",
      "Tourism Boards",
      "Car Rental",
      "Trains",
      "Buses",
      "Ferries",
      "Airport Parking",
      "Luggage",
      "Travel Insurance",
      "Travel eSIMs",
      "Travel Credit Cards",
      "Visa Services",
      "Business Travel",
      "Honeymoons",
      "Luxury Travel",
      "Backpacking",
    ],
  },
  {
    name: "Entertainment & Events",
    categories: [
      "Events",
      "Concerts",
      "Festivals",
      "Ticketing",
      "Theater",
      "Comedy",
      "Movies",
      "Cinema",
      "TV Shows",
      "Music Artists",
      "Museums",
      "Libraries",
      "Theme Parks",
      "Water Parks",
      "Zoos",
      "Escape Rooms",
      "Bowling",
    ],
  },
  {
    name: "Media & Streaming",
    categories: [
      "Streaming Services",
      "Music Streaming",
      "Podcasts",
      "Audiobooks",
      "Books",
      "News Media",
      "Magazines",
      "Subscriptions",
      "Social Media Platforms",
      "Creator Economy",
      "Influencer Marketing",
    ],
  },
  {
    name: "Gaming",
    categories: [
      "Gaming",
      "Mobile Games",
      "PC Gaming",
      "Console Gaming",
      "Esports",
      "Gaming Accessories",
      "Gaming Chairs",
      "Board Games",
    ],
  },
  {
    name: "Gambling & Regulated",
    categories: [
      "Gambling",
      "Casinos",
      "Sports Betting",
      "Fantasy Sports",
      "Lottery",
      "Bingo",
      "Cannabis",
      "CBD",
      "Vaping",
      "Tobacco Alternatives",
    ],
  },
  {
    name: "Automotive & Mobility",
    categories: [
      "Automotive",
      "Car Brands",
      "Used Cars",
      "Car Dealerships",
      "Electric Vehicles",
      "EV Charging",
      "Car Parts",
      "Tires",
      "Car Care",
      "Car Insurance",
      "Fuel",
      "Trucks",
      "RVs",
      "Boats",
      "Motorcycles",
      "E-Bikes",
      "Bicycles",
      "Scooters",
      "Ride-Hailing",
      "Car Sharing",
      "Public Transport",
    ],
  },
  {
    name: "Consumer Tech",
    categories: [
      "Technology",
      "Consumer Electronics",
      "Smartphones",
      "Phone Accessories",
      "Chargers",
      "Power Banks",
      "Laptops",
      "Tablets",
      "Monitors",
      "PC Components",
      "Keyboards",
      "Printers",
      "3D Printers",
      "TVs",
      "Audio",
      "Headphones",
      "Smart Speakers",
      "Cameras",
      "Drones",
      "Wearables",
      "Smartwatches",
      "VR",
      "Routers",
    ],
  },
  {
    name: "Software & SaaS",
    categories: [
      "SaaS",
      "AI Tools",
      "Cloud Computing",
      "Web Hosting",
      "Domain Names",
      "Website Builders",
      "No-Code Tools",
      "Developer Tools",
      "Design Software",
      "Photo Editing Apps",
      "Productivity Apps",
      "Project Management Software",
      "CRM Software",
      "HR Software",
      "Payroll",
      "Accounting Software",
      "Invoicing",
      "E-signature",
      "Email Marketing Software",
      "Analytics Software",
      "Cybersecurity",
      "Antivirus",
      "VPN",
      "Password Managers",
      "Mobile Apps",
    ],
  },
  {
    name: "Finance & Insurance",
    categories: [
      "Finance",
      "Fintech",
      "Banking",
      "Neobanks",
      "Business Banking",
      "Credit Cards",
      "Loans",
      "Business Loans",
      "Mortgages",
      "Buy Now Pay Later",
      "Payments",
      "Point of Sale",
      "Remittances",
      "Forex",
      "Investing",
      "Stock Trading",
      "Cryptocurrency",
      "Precious Metals",
      "Wealth Management",
      "Retirement Planning",
      "Pensions",
      "Crowdfunding",
      "Personal Finance Apps",
      "Tax Services",
      "Debt Relief",
      "Credit Repair",
      "Insurance",
      "Life Insurance",
      "Health Insurance",
      "Home Insurance",
    ],
  },
  {
    name: "Education & Careers",
    categories: [
      "Education",
      "Edtech",
      "E-learning",
      "Online Courses",
      "Webinars",
      "Language Learning",
      "Test Prep",
      "Tutoring",
      "K-12 Education",
      "Kids' Learning Apps",
      "Universities",
      "Study Abroad",
      "Coding Bootcamps",
      "Professional Certifications",
      "Music Lessons",
      "Driving Schools",
      "Job Boards",
      "Recruitment",
      "Staffing Agencies",
      "Career Coaching",
      "Freelancing Platforms",
    ],
  },
  {
    name: "Business Services",
    categories: [
      "B2B Services",
      "Startups",
      "Franchises",
      "Marketing Agencies",
      "Advertising Platforms",
      "Consulting",
      "Legal Services",
      "Translation Services",
      "E-commerce Platforms",
      "Marketplaces",
      "Dropshipping",
      "Print on Demand",
      "Printing Services",
      "Packaging",
      "Logistics",
      "Shipping",
      "Manufacturing",
      "Office Supplies",
      "Coworking Spaces",
      "Telecom",
      "Internet Providers",
      "Utilities",
    ],
  },
  {
    name: "Sustainability",
    categories: [
      "Sustainability",
      "Eco-Friendly Products",
      "Zero Waste",
      "Recycling",
      "Secondhand Resale",
      "Refurbished Electronics",
      "Solar Energy",
      "Renewable Energy",
    ],
  },
  {
    name: "Public Sector & Causes",
    categories: [
      "Government",
      "Elections",
      "Political Campaigns",
      "Advocacy",
      "Public Health Campaigns",
      "Anti-Smoking",
      "Road Safety",
      "Blood Donation",
      "Climate Campaigns",
      "Animal Welfare",
      "Humanitarian Aid",
      "Charity",
      "Nonprofits",
      "Military Recruitment",
      "Police Recruitment",
    ],
  },
  {
    name: "Other",
    categories: [
      "Other",
    ],
  },
];

export const CATEGORY_OPTIONS = CATEGORY_GROUPS.flatMap((g) => g.categories);

const GROUP_OF = new Map(
  CATEGORY_GROUPS.flatMap((g) => g.categories.map((c) => [c, g.name] as const))
);

export function categoryGroup(category: string): string | undefined {
  return GROUP_OF.get(category);
}

// The most categories one ad can be in.
export const MAX_CATEGORIES = 3;

// All of an ad's categories, primary first. Ads from before multiple
// categories (or an older API) only have `category`.
export function adCategories(ad: { category: string; categories?: string[] }): string[] {
  return ad.categories?.length ? ad.categories : [ad.category];
}

// Names that aren't categories themselves but mean one: the 20 categories
// used before this taxonomy (existing ads were moved over by the
// 20261007140000_new_categories migration, but old links and CSVs still
// carry them), and template names the taxonomy merged.
export const CATEGORY_ALIASES: Record<string, string> = {
  "E-commerce / DTC": "Other",
  "Fashion & Apparel": "Fashion",
  "Jewelry & Accessories": "Jewelry",
  "Beauty & Skincare": "Skincare",
  "Personal care / Grooming": "Men's Grooming",
  "Health & Fitness": "Health",
  "Food & Beverage": "Food",
  "Home & Living": "Home Decor",
  "Parenting & Baby": "Parenting",
  "Sustainability & Eco": "Sustainability",
  "SaaS & Tech": "SaaS",
  "Apps & Subscriptions": "Mobile Apps",
  "Gaming & Creator": "Gaming",
  "Finance & Fintech": "Fintech",
  "Education & E-learning": "E-learning",
  "Skiing Gear": "Skiing",
  "Ski Resorts": "Skiing",
  "Funeral Services": "Funerals",
  "Aquarium Attractions": "Zoos",
};

// The category a typed or linked name means, ignoring case, or undefined.
export function findCategory(value: string): string | undefined {
  const norm = value.trim().toLowerCase();
  if (!norm) return undefined;
  const direct = CATEGORY_OPTIONS.find((c) => c.toLowerCase() === norm);
  if (direct) return direct;
  const alias = Object.keys(CATEGORY_ALIASES).find(
    (k) => k.toLowerCase() === norm
  );
  return alias ? CATEGORY_ALIASES[alias] : undefined;
}
